#!/bin/bash

set -e

echo "This script has no capability to add packages to vm images"
echo "Please check the other approaches"
exit -1

compile_packages="gcc binutils make"

basedir=$(dirname $(readlink -f $0))
. ${basedir}/config/env.sh

check_availability_of() {
	prog=$1
	if ! command -v ${prog} 2>&1 > /dev/null; then
		echo "$prog not found in path. Please install and try again."
		exit 1
	fi
}

check_availability_of sudo
check_availability_of chroot

if [ ! -e ${rootfs} ]; then
	sudo mkdir ${rootfs}
fi

if [ ! -e ${basedir}/${img} ]; then
	echo "You should make ${basedir}/${img} first"
	exit -1
fi

echo -n "Mounting ${rootfs} on loopback... "
sudo mount -o loop ${basedir}/${img} ${rootfs}
echo "ok"

if test ! -z "${compile_packages}"; then
	echo "Installing additional packages... "
	sudo sh -c "chroot ${rootfs} apt-get update"
	sudo sh -c "chroot ${rootfs} apt-get install -y ${compile_packages}"
fi

sudo umount ${rootfs}
sudo rmdir ${rootfs}
